# Generated by Django 3.0.3 on 2020-08-21 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('idMinuta', models.AutoField(primary_key=True, serialize=False)),
                ('Minuta', models.IntegerField()),
                ('DataMinuta', models.DateField(default=0)),
                ('HoraInicial', models.TimeField(default=datetime.time(0, 0))),
                ('HoraFinal', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('Coleta', models.TextField(blank=True)),
                ('Entrega', models.TextField(blank=True)),
                ('KMInicial', models.IntegerField(default=0)),
                ('KMFinal', models.IntegerField(default=0)),
                ('Obs', models.TextField(blank=True)),
                ('StatusMinuta', models.CharField(default='ABERTA', max_length=10)),
                ('idCategoriaVeiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.CategoriaVeiculo')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('idVeiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.Veiculo')),
            ],
            options={
                'db_table': 'Minuta',
                'ordering': ['Minuta'],
            },
        ),
        migrations.CreateModel(
            name='MinutaItens',
            fields=[
                ('idMinutaItens', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=25)),
                ('TipoItens', models.CharField(max_length=5)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Quantidade', models.IntegerField(default=0)),
                ('Porcento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Tempo', models.DurationField(default=0)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minuta')),
            ],
            options={
                'db_table': 'MinutaItens',
            },
        ),
        migrations.CreateModel(
            name='MinutaFatura',
            fields=[
                ('idMinutaFatura', models.AutoField(primary_key=True, serialize=False)),
                ('DataFatura', models.DateField(default=0)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ValorPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ValorDesconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DataPtgo', models.DateField(default=0)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minuta')),
            ],
            options={
                'db_table': 'MinutaFatura',
            },
        ),
        migrations.CreateModel(
            name='MinutaColaboradores',
            fields=[
                ('idMinutaColaboradores', models.AutoField(primary_key=True, serialize=False)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minuta')),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.Pessoal')),
            ],
            options={
                'db_table': 'MinutaColaboradores',
            },
        ),
    ]
