# Generated by Django 3.1.3 on 2021-07-12 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('faturamentos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('idMinuta', models.AutoField(primary_key=True, serialize=False)),
                ('Minuta', models.IntegerField()),
                ('DataMinuta', models.DateField(default=0)),
                ('HoraInicial', models.TimeField(default=datetime.time(0, 0))),
                ('HoraFinal', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('Coleta', models.TextField(blank=True)),
                ('Entrega', models.TextField(blank=True)),
                ('KMInicial', models.IntegerField(default=0)),
                ('KMFinal', models.IntegerField(default=0)),
                ('Obs', models.TextField(blank=True)),
                ('StatusMinuta', models.CharField(default='ABERTA', max_length=10)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Comentarios', models.TextField(blank=True, default='')),
                ('idCategoriaVeiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.categoriaveiculo')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('idFatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturamentos.fatura')),
                ('idVeiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo')),
            ],
            options={
                'db_table': 'Minuta',
                'ordering': ['Minuta'],
            },
        ),
        migrations.CreateModel(
            name='MinutaNotas',
            fields=[
                ('idMinutaNotas', models.AutoField(primary_key=True, serialize=False)),
                ('Nota', models.CharField(max_length=10)),
                ('ValorNota', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Peso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Volume', models.IntegerField(default=0)),
                ('Nome', models.CharField(blank=True, max_length=60, null=True)),
                ('Estado', models.CharField(default='SP', max_length=2)),
                ('Cidade', models.CharField(default='SÃO PAULO', max_length=30)),
                ('Bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('NotaGuia', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.minuta')),
            ],
            options={
                'db_table': 'MinutaNotas',
            },
        ),
        migrations.CreateModel(
            name='MinutaItens',
            fields=[
                ('idMinutaItens', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=25)),
                ('TipoItens', models.CharField(max_length=9)),
                ('RecebePaga', models.CharField(max_length=1)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Quantidade', models.IntegerField(default=0)),
                ('Porcento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Peso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ValorBase', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Tempo', models.DurationField(default=0)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.minuta')),
            ],
            options={
                'db_table': 'MinutaItens',
            },
        ),
        migrations.CreateModel(
            name='MinutaColaboradores',
            fields=[
                ('idMinutaColaboradores', models.AutoField(primary_key=True, serialize=False)),
                ('Cargo', models.CharField(max_length=10)),
                ('Pago', models.BooleanField(default=False)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.minuta')),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'MinutaColaboradores',
            },
        ),
    ]
