# Generated by Django 3.1.3 on 2021-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutacolaboradores',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
    ]
