# Generated by Django 3.1.3 on 2021-11-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('clientes', '0002_auto_20211105_1305'),
        ('faturamentos', '0001_initial'),
        ('minutas', '0001_initial'),
        ('pagamentos', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutacolaboradores',
            name='idPessoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal'),
        ),
        migrations.AddField(
            model_name='minutacolaboradores',
            name='idRecibo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.recibo'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='idCategoriaVeiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.categoriaveiculo'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='idFatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturamentos.fatura'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='idVeiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo'),
        ),
    ]
