# Generated by Django 3.1.3 on 2021-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaitens',
            name='Tempo2',
            field=models.DurationField(default=0),
        ),
    ]
