# Generated by Django 3.0.3 on 2020-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutacolaboradores',
            name='Cargo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
