# Generated by Django 3.1.3 on 2021-01-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanotas',
            name='Bairro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
