# Generated by Django 3.1.3 on 2021-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutaitens',
            name='idRecibo',
        ),
    ]
