# Generated by Django 3.1.3 on 2021-11-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0002_auto_20211105_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutaitens',
            name='Obs',
        ),
    ]
