# Generated by Django 3.1.3 on 2021-07-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        ('minutas', '0002_remove_minutaitens_idrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaitens',
            name='idRecibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.recibo'),
        ),
    ]
