# Generated by Django 3.0.3 on 2020-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0002_minutacolaboradores_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='TipoItens',
            field=models.CharField(max_length=8),
        ),
    ]
