# Generated by Django 3.1.3 on 2021-07-13 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0002_minutaitens_tempo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Tempo2',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
