# Generated by Django 3.1.3 on 2021-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0002_minutanotas_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='Bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
