# Generated by Django 3.1.3 on 2021-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_remove_minutaitens_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaitens',
            name='Obs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
