# Generated by Django 3.1.3 on 2021-07-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_auto_20210730_1026'),
        ('minutas', '0003_minutaitens_idrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutacolaboradores',
            name='idRecibo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.recibo'),
        ),
    ]
