# Generated by Django 3.1.3 on 2021-07-13 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_auto_20210713_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Tempo',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
