# Generated by Django 3.0.3 on 2020-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_auto_20200831_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaitens',
            name='RecebePaga',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
