# Generated by Django 3.1.3 on 2021-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0004_minutacolaboradores_idrecibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutaitens',
            name='idRecibo',
        ),
    ]
