# Generated by Django 3.0.3 on 2020-10-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0004_minutaitens_recebepaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaNotas',
            fields=[
                ('idMinutaNotas', models.AutoField(primary_key=True, serialize=False)),
                ('Nota', models.CharField(max_length=10)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Peso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Volume', models.IntegerField(default=0)),
                ('idMinuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minuta')),
            ],
            options={
                'db_table': 'MinutaNotas',
            },
        ),
    ]
