# Generated by Django 3.1.3 on 2021-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0004_auto_20210713_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutaitens',
            name='Tempo2',
        ),
        migrations.AlterField(
            model_name='minutaitens',
            name='Tempo',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
