# Generated by Django 3.1.3 on 2021-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0005_auto_20210713_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Tempo',
            field=models.DurationField(default=0),
        ),
    ]
