# Generated by Django 3.1.3 on 2021-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0005_remove_minutaitens_idrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanotas',
            name='ExtraValorAjudante',
            field=models.BooleanField(default=False),
        ),
    ]
