# Generated by Django 3.0.3 on 2020-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0005_minutanotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaitens',
            name='Peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='minutaitens',
            name='ValorBase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
