# Generated by Django 3.1.3 on 2022-07-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0005_auto_20220221_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='Nota',
            field=models.CharField(max_length=100),
        ),
    ]
