# Generated by Django 3.1.3 on 2023-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0006_auto_20220727_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Porcento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
