# Generated by Django 3.1.3 on 2021-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0006_minutanotas_extravalorajudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='ExtraValorAjudante',
            field=models.IntegerField(default=0),
        ),
    ]
