# Generated by Django 3.0.3 on 2020-11-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0006_auto_20201023_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanotas',
            name='Cidade',
            field=models.CharField(default='SÃO PAULO', max_length=60),
        ),
        migrations.AddField(
            model_name='minutanotas',
            name='Estado',
            field=models.CharField(default='SP', max_length=60),
        ),
        migrations.AddField(
            model_name='minutanotas',
            name='Nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='minutanotas',
            name='NotaGuia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
