# Generated by Django 3.1.3 on 2020-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0007_auto_20201112_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='Cidade',
            field=models.CharField(blank=True, default='SÃO PAULO', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='minutanotas',
            name='Estado',
            field=models.CharField(blank=True, default='SP', max_length=60, null=True),
        ),
    ]
