# Generated by Django 3.1.3 on 2021-10-25 16:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0007_auto_20210804_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('idCategoriaDespesa', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=25)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
