# Generated by Django 3.1.3 on 2024-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0007_auto_20230410_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Descricao',
            field=models.CharField(max_length=30),
        ),
    ]
