# Generated by Django 3.1.3 on 2021-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0008_categoriadespesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanotas',
            name='Obs',
            field=models.TextField(blank=True, default=None),
        ),
    ]
