# Generated by Django 3.1.3 on 2020-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0008_auto_20201116_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='TipoItens',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='minutanotas',
            name='NotaGuia',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
