# Generated by Django 3.1.3 on 2024-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0008_auto_20240717_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutanotas',
            name='id_romaneio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
