# Generated by Django 3.1.3 on 2020-11-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0009_auto_20201117_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='Cidade',
            field=models.CharField(default='SÃO PAULO', max_length=60),
        ),
        migrations.AlterField(
            model_name='minutanotas',
            name='Estado',
            field=models.CharField(default='SP', max_length=60),
        ),
    ]
