# Generated by Django 3.1.3 on 2020-11-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0010_auto_20201117_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutanotas',
            name='Cidade',
            field=models.CharField(default='SÃO PAULO', max_length=30),
        ),
        migrations.AlterField(
            model_name='minutanotas',
            name='Estado',
            field=models.CharField(default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='minutanotas',
            name='Nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
