# Generated by Django 3.1.3 on 2021-10-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0010_minutaitens_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutanotas',
            name='Obs',
        ),
    ]
