# Generated by Django 3.1.3 on 2021-10-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0011_remove_minutanotas_obs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaDespesa',
        ),
    ]
