# Generated by Django 3.1.3 on 2020-11-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0001_initial'),
        ('minutas', '0011_auto_20201117_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutafatura',
            name='DataFatura',
        ),
        migrations.RemoveField(
            model_name='minutafatura',
            name='DataPtgo',
        ),
        migrations.RemoveField(
            model_name='minutafatura',
            name='ValorDesconto',
        ),
        migrations.RemoveField(
            model_name='minutafatura',
            name='ValorPago',
        ),
        migrations.AddField(
            model_name='minutafatura',
            name='Comentarios',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minutafatura',
            name='idFatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturamentos.fatura'),
        ),
    ]
