# Generated by Django 3.1.3 on 2021-11-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0012_delete_categoriadespesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutaitens',
            name='Obs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
