# Generated by Django 3.1.3 on 2020-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0012_auto_20201118_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutafatura',
            name='Comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
