# Generated by Django 3.1.3 on 2020-11-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0013_auto_20201119_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutanotas',
            old_name='Valor',
            new_name='ValorNota',
        ),
    ]
