# Generated by Django 3.1.3 on 2020-12-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0002_fatura_statusfatura'),
        ('minutas', '0014_auto_20201120_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='Comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minuta',
            name='Valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='minuta',
            name='idFatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturamentos.fatura'),
        ),
        migrations.DeleteModel(
            name='MinutaFatura',
        ),
    ]
