# Generated by Django 3.1.3 on 2020-12-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0015_auto_20201130_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuta',
            name='Comentarios',
            field=models.TextField(blank=True, default=''),
        ),
    ]
