# Generated by Django 3.1.3 on 2021-02-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='idPessoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal'),
            preserve_default=False,
        ),
    ]
