# Generated by Django 3.1.3 on 2021-07-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboItens',
            fields=[
                ('idReciboItens', models.AutoField(primary_key=True, serialize=False)),
                ('idRecibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.recibo')),
            ],
            options={
                'db_table': 'idRecibo',
            },
        ),
    ]
