# Generated by Django 3.1.3 on 2021-07-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_minutaitens_idrecibo'),
        ('pagamentos', '0002_reciboitens'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboitens',
            name='idMinutaItens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='minutas.minutaitens'),
            preserve_default=False,
        ),
    ]
