# Generated by Django 3.1.3 on 2022-02-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_recibo_idpessoal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recibo',
            table='recibo',
        ),
        migrations.AlterModelTable(
            name='reciboitens',
            table='reciboitens',
        ),
    ]
