# Generated by Django 3.1.3 on 2021-03-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('minutas', '0001_initial'),
        ('pagamentos', '0002_recibo_idpessoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboItens',
            fields=[
                ('idReciboItens', models.AutoField(primary_key=True, serialize=False)),
                ('idMinutaItens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='minutas.minutaitens')),
                ('idRecibo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.recibo')),
                ('idVales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.vales')),
            ],
            options={
                'db_table': 'RecibovItens',
            },
        ),
        migrations.DeleteModel(
            name='ItensRecibo',
        ),
    ]
