# Generated by Django 3.1.3 on 2023-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_auto_20220221_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('idFolhaPagamento', models.AutoField(primary_key=True, serialize=False)),
                ('MesReferencia', models.CharField(max_length=9)),
                ('AnoReferencia', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Colaboradores', models.IntegerField()),
                ('Pago', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'folha_pagamento',
            },
        ),
    ]
