# Generated by Django 3.1.3 on 2021-07-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_reciboitens_idminutaitens'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reciboitens',
            table='ReciboItens',
        ),
    ]
