# Generated by Django 3.1.3 on 2021-02-16 03:10

from django.db import migrations, models
import django.db.models.deletion
import pessoas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('idPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Endereco', models.CharField(blank=True, max_length=60)),
                ('Bairro', models.CharField(blank=True, max_length=20)),
                ('CEP', models.CharField(blank=True, max_length=9)),
                ('Cidade', models.CharField(blank=True, default='SÃO PAULO', max_length=25)),
                ('Estado', models.CharField(blank=True, default='SP', max_length=2)),
                ('DataNascimento', models.DateField(blank=True, null=True)),
                ('Mae', models.CharField(blank=True, max_length=50, null=True)),
                ('Pai', models.CharField(blank=True, max_length=50, null=True)),
                ('Categoria', models.CharField(max_length=15)),
                ('TipoPgto', models.CharField(max_length=25)),
                ('StatusPessoal', models.BooleanField(default=True)),
                ('DataAdmissao', models.DateField(blank=True, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=pessoas.models.get_file_path)),
            ],
            options={
                'db_table': 'Pessoal',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='Vales',
            fields=[
                ('idVales', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Descricao', models.CharField(max_length=100)),
                ('Valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('idPessoal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'Vales',
                'ordering': ['idPessoal', 'Data', 'Descricao'],
            },
        ),
        migrations.CreateModel(
            name='HorasTrabalhadas',
            fields=[
                ('idHorasTrabalhadas', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Minuta', models.CharField(max_length=6)),
                ('HoraInicial', models.TimeField()),
                ('HoraFinal', models.TimeField()),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'HorasTrabalhadas',
                'ordering': ['idPessoal', 'Data', 'Minuta'],
            },
        ),
        migrations.CreateModel(
            name='HorasConfig',
            fields=[
                ('idHorasConfig', models.AutoField(primary_key=True, serialize=False)),
                ('Salario', models.DecimalField(decimal_places=2, default=1.0, max_digits=9)),
                ('HorasMensais', models.DurationField()),
                ('idPessoal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'HorasConfig',
                'ordering': ['idPessoal'],
            },
        ),
        migrations.CreateModel(
            name='FonePessoal',
            fields=[
                ('idFonePessoal', models.AutoField(primary_key=True, serialize=False)),
                ('TipoFone', models.CharField(max_length=15)),
                ('Fone', models.CharField(max_length=20)),
                ('Contato', models.CharField(blank=True, max_length=50)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'FonePessoal',
                'ordering': ['TipoFone'],
            },
        ),
        migrations.CreateModel(
            name='DocPessoal',
            fields=[
                ('idDocPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocumento', models.CharField(max_length=25)),
                ('Documento', models.CharField(max_length=25)),
                ('Data', models.DateField(blank=True, null=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'DocPessoal',
                'ordering': ['TipoDocumento'],
            },
        ),
        migrations.CreateModel(
            name='ContaPessoal',
            fields=[
                ('idContaPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('Banco', models.CharField(blank=True, max_length=20)),
                ('Agencia', models.CharField(blank=True, max_length=6)),
                ('Conta', models.CharField(blank=True, max_length=10)),
                ('TipoConta', models.CharField(blank=True, max_length=8)),
                ('Titular', models.CharField(blank=True, max_length=50)),
                ('Documento', models.CharField(blank=True, max_length=25)),
                ('PIX', models.CharField(blank=True, max_length=50)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'ContaPessoal',
                'ordering': ['idPessoal', 'Banco', 'Agencia', 'Conta', 'PIX'],
            },
        ),
    ]
