# Generated by Django 3.1.3 on 2021-11-05 14:14

from django.db import migrations, models
import django.db.models.deletion
import pessoas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraCheque',
            fields=[
                ('idContraCheque', models.AutoField(primary_key=True, serialize=False)),
                ('MesReferencia', models.CharField(max_length=9)),
                ('AnoReferencia', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Pago', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ContraCheque',
                'ordering': ['-idContraCheque'],
            },
        ),
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('idPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Endereco', models.CharField(blank=True, max_length=60)),
                ('Bairro', models.CharField(blank=True, max_length=20)),
                ('CEP', models.CharField(blank=True, max_length=9)),
                ('Cidade', models.CharField(blank=True, default='SÃO PAULO', max_length=25)),
                ('Estado', models.CharField(blank=True, default='SP', max_length=2)),
                ('DataNascimento', models.DateField(blank=True, null=True)),
                ('Mae', models.CharField(blank=True, max_length=50, null=True)),
                ('Pai', models.CharField(blank=True, max_length=50, null=True)),
                ('Categoria', models.CharField(max_length=15)),
                ('TipoPgto', models.CharField(max_length=25)),
                ('StatusPessoal', models.BooleanField(default=True)),
                ('DataAdmissao', models.DateField(blank=True, null=True)),
                ('DataDemissao', models.DateField(blank=True, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=pessoas.models.get_file_path)),
            ],
            options={
                'db_table': 'Pessoal',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='Vales',
            fields=[
                ('idVales', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Descricao', models.CharField(max_length=100)),
                ('Valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('Pago', models.BooleanField(default=False)),
                ('idPessoal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
                ('idRecibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.recibo')),
            ],
            options={
                'db_table': 'Vales',
                'ordering': ['idPessoal', 'Data', 'Descricao'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('idSalario', models.AutoField(primary_key=True, serialize=False)),
                ('Salario', models.DecimalField(decimal_places=2, default=1.0, max_digits=9)),
                ('HorasMensais', models.DecimalField(decimal_places=2, default=220.0, max_digits=6)),
                ('ValeTransporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('idPessoal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'Salario',
                'ordering': ['idPessoal'],
            },
        ),
        migrations.CreateModel(
            name='HorasTrabalhadas',
            fields=[
                ('idHorasTrabalhadas', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Minuta', models.CharField(max_length=6)),
                ('HoraInicial', models.TimeField()),
                ('HoraFinal', models.TimeField()),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'HorasTrabalhadas',
                'ordering': ['idPessoal', 'Data', 'Minuta'],
            },
        ),
        migrations.CreateModel(
            name='FonePessoal',
            fields=[
                ('idFonePessoal', models.AutoField(primary_key=True, serialize=False)),
                ('TipoFone', models.CharField(max_length=15)),
                ('Fone', models.CharField(max_length=20)),
                ('Contato', models.CharField(blank=True, max_length=50)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'FonePessoal',
                'ordering': ['TipoFone'],
            },
        ),
        migrations.CreateModel(
            name='DocPessoal',
            fields=[
                ('idDocPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocumento', models.CharField(max_length=25)),
                ('Documento', models.CharField(max_length=25)),
                ('Data', models.DateField(blank=True, null=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'DocPessoal',
                'ordering': ['TipoDocumento'],
            },
        ),
        migrations.CreateModel(
            name='ContraChequeItens',
            fields=[
                ('idContraChequeItens', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.TextField(max_length=50)),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Registro', models.CharField(max_length=1)),
                ('Referencia', models.CharField(blank=True, max_length=10)),
                ('Vales_id', models.IntegerField(default=0)),
                ('idContraCheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.contracheque')),
            ],
            options={
                'db_table': 'ContraChequeItens',
                'ordering': ['Descricao'],
            },
        ),
        migrations.AddField(
            model_name='contracheque',
            name='idPessoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal'),
        ),
        migrations.CreateModel(
            name='ContaPessoal',
            fields=[
                ('idContaPessoal', models.AutoField(primary_key=True, serialize=False)),
                ('Banco', models.CharField(blank=True, max_length=20)),
                ('Agencia', models.CharField(blank=True, max_length=6)),
                ('Conta', models.CharField(blank=True, max_length=10)),
                ('TipoConta', models.CharField(blank=True, max_length=8)),
                ('Titular', models.CharField(blank=True, max_length=50)),
                ('Documento', models.CharField(blank=True, max_length=25)),
                ('PIX', models.CharField(blank=True, max_length=50)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'ContaPessoal',
                'ordering': ['idPessoal', 'Banco', 'Agencia', 'Conta', 'PIX'],
            },
        ),
        migrations.CreateModel(
            name='CartaoPonto',
            fields=[
                ('idCartaoPonto', models.AutoField(primary_key=True, serialize=False)),
                ('Dia', models.DateField()),
                ('Entrada', models.TimeField()),
                ('Saida', models.TimeField()),
                ('Ausencia', models.CharField(blank=True, max_length=7)),
                ('Alteracao', models.CharField(default='ROBOT', max_length=6)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'CartaoPonto',
                'ordering': ['Dia'],
            },
        ),
    ]
