# Generated by Django 3.1.3 on 2021-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
    ]
