# Generated by Django 3.1.3 on 2021-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapessoal',
            options={'ordering': ['idPessoal', 'Banco', 'Agencia', 'Conta', 'PIX']},
        ),
        migrations.AddField(
            model_name='contapessoal',
            name='PIX',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
