# Generated by Django 3.1.3 on 2021-03-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('idSalario', models.AutoField(primary_key=True, serialize=False)),
                ('Salario', models.DecimalField(decimal_places=2, default=1.0, max_digits=9)),
                ('HorasMensais', models.DurationField()),
                ('idPessoal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'Salario',
                'ordering': ['idPessoal'],
            },
        ),
        migrations.DeleteModel(
            name='HorasConfig',
        ),
    ]
