# Generated by Django 3.1.3 on 2022-02-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartaoponto',
            table='cartaoponto',
        ),
        migrations.AlterModelTable(
            name='contapessoal',
            table='contapessoal',
        ),
        migrations.AlterModelTable(
            name='contracheque',
            table='contracheque',
        ),
        migrations.AlterModelTable(
            name='contrachequeitens',
            table='contrachequeitens',
        ),
        migrations.AlterModelTable(
            name='docpessoal',
            table='docpessoal',
        ),
        migrations.AlterModelTable(
            name='fonepessoal',
            table='fonepessoal',
        ),
        migrations.AlterModelTable(
            name='horastrabalhadas',
            table='horastrabalhadas',
        ),
        migrations.AlterModelTable(
            name='pessoal',
            table='pessoal',
        ),
        migrations.AlterModelTable(
            name='salario',
            table='salario',
        ),
        migrations.AlterModelTable(
            name='vales',
            table='vales',
        ),
    ]
