# Generated by Django 3.1.3 on 2021-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20210316_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='HorasMensais',
            field=models.DecimalField(decimal_places=2, default=220.0, max_digits=6),
        ),
    ]
