# Generated by Django 3.1.3 on 2021-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20210122_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoal',
            name='StatusPessoal',
            field=models.BooleanField(default=True),
        ),
    ]
