# Generated by Django 3.1.3 on 2022-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20220221_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoponto',
            name='Conducao',
            field=models.BooleanField(default=False),
        ),
    ]
