# Generated by Django 3.1.3 on 2022-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_cartaoponto_conducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoponto',
            name='Remunerado',
            field=models.BooleanField(default=True),
        ),
    ]
