# Generated by Django 3.1.3 on 2021-03-21 13:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20210319_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraCheque',
            fields=[
                ('idContraCheque', models.AutoField(primary_key=True, serialize=False)),
                ('MesReferencia', models.TextField(max_length=10)),
                ('AnoReferencia', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'db_table': 'ContraCheque',
                'ordering': ['AnoReferencia', 'MesReferencia'],
            },
        ),
        migrations.CreateModel(
            name='ContraChequeItens',
            fields=[
                ('idContraChequeItens', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.TextField(max_length=50)),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'db_table': 'ContraChequeItens',
                'ordering': ['Descricao'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
