# Generated by Django 3.1.3 on 2021-04-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20210413_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraCheque',
            fields=[
                ('idContraCheque', models.AutoField(primary_key=True, serialize=False)),
                ('MesReferencia', models.CharField(max_length=9)),
                ('AnoReferencia', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Pago', models.BooleanField(default=False)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'ContraCheque',
                'ordering': ['-idContraCheque'],
            },
        ),
        migrations.CreateModel(
            name='ContraChequeItens',
            fields=[
                ('idContraChequeItens', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.TextField(max_length=50)),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Registro', models.CharField(max_length=1)),
                ('idContraCheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.contracheque')),
            ],
            options={
                'db_table': 'ContraChequeItens',
                'ordering': ['Descricao'],
            },
        ),
    ]
