# Generated by Django 3.1.3 on 2021-01-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoal_statuspessoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonepessoal',
            name='Fone',
            field=models.CharField(max_length=20),
        ),
    ]
