# Generated by Django 3.1.3 on 2021-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_auto_20210127_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoal',
            name='DataAdmissão',
            field=models.DateField(blank=True, null=True),
        ),
    ]
