# Generated by Django 3.1.3 on 2022-05-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_cartaoponto_remunerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaoponto',
            name='Conducao',
        ),
        migrations.RemoveField(
            model_name='cartaoponto',
            name='Remunerado',
        ),
    ]
