# Generated by Django 3.1.3 on 2021-04-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_contracheque_contrachequeitens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrachequeitens',
            name='idContraCheque',
        ),
        migrations.DeleteModel(
            name='ContraCheque',
        ),
        migrations.DeleteModel(
            name='ContraChequeItens',
        ),
    ]
