# Generated by Django 3.1.3 on 2021-03-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_contracheque_contrachequeitens'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='idPessoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrachequeitens',
            name='idContraCheque',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pessoas.contracheque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='MesReferencia',
            field=models.CharField(max_length=10),
        ),
    ]
