# Generated by Django 3.1.3 on 2022-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_auto_20220517_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoponto',
            name='Conducao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartaoponto',
            name='Remunerado',
            field=models.BooleanField(default=True),
        ),
    ]
