# Generated by Django 3.1.3 on 2021-01-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoal_dataadmissão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoal',
            old_name='DataAdmissão',
            new_name='DataAdmissao',
        ),
    ]
