# Generated by Django 3.1.3 on 2021-04-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_contracheque_contrachequeitens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoPonto',
            fields=[
                ('idCartaPonto', models.AutoField(primary_key=True, serialize=False)),
                ('Dia', models.DateField()),
                ('Entrada', models.TimeField()),
                ('Saida', models.TimeField()),
                ('Ausencia', models.CharField(blank=True, max_length=7)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'CartaoPonto',
                'ordering': ['Dia'],
            },
        ),
    ]
