# Generated by Django 3.1.3 on 2021-01-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20210127_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapessoal',
            name='Agencia',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='contapessoal',
            name='Banco',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contapessoal',
            name='Conta',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contapessoal',
            name='PIX',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
