# Generated by Django 3.1.3 on 2022-05-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20220517_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoponto',
            name='CarroEmpresa',
            field=models.BooleanField(default=False),
        ),
    ]
