# Generated by Django 3.1.3 on 2021-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20210329_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracheque',
            name='MesReferencia',
            field=models.CharField(max_length=9),
        ),
    ]
