# Generated by Django 3.1.3 on 2022-05-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_cartaoponto_carroempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('Dia', models.DateField()),
                ('Descricao', models.TextField(max_length=240)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'agenda',
                'ordering': ['Dia'],
            },
        ),
    ]
