# Generated by Django 3.1.3 on 2021-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_auto_20210329_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracheque',
            options={'ordering': ['-idContraCheque']},
        ),
        migrations.AddField(
            model_name='contrachequeitens',
            name='Registro',
            field=models.CharField(default='C', max_length=1),
            preserve_default=False,
        ),
    ]
