# Generated by Django 3.1.3 on 2021-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_auto_20210127_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoal',
            name='Endereco',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
