# Generated by Django 3.1.3 on 2021-04-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_cartaoponto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaoponto',
            old_name='idCartaPonto',
            new_name='idCartaoPonto',
        ),
    ]
