# Generated by Django 3.1.3 on 2021-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_auto_20210428_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoponto',
            name='Alteracao',
            field=models.CharField(default='ROBOT', max_length=6),
        ),
    ]
