# Generated by Django 3.1.3 on 2022-11-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecimoTerceiro',
            fields=[
                ('idDecimoTerceiro', models.AutoField(primary_key=True, serialize=False)),
                ('Ano', models.IntegerField(default=0)),
                ('Dozeavos', models.IntegerField(default=0)),
                ('ValorBase', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Pago', models.BooleanField(default=False)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'decimo_terceiro',
                'ordering': ['Ano', 'Valor'],
            },
        ),
        migrations.CreateModel(
            name='ParcelasDecimoTerceiro',
            fields=[
                ('idParcelasDecimoTerceiro', models.AutoField(primary_key=True, serialize=False)),
                ('Parcela', models.IntegerField(default=0)),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Pago', models.BooleanField(default=False)),
                ('DataPgto', models.DateField(blank=True, null=True)),
                ('idDecimoTerceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.decimoterceiro')),
            ],
            options={
                'db_table': 'decimo_terceiro_parcelas',
                'ordering': ['idParcelasDecimoTerceiro'],
            },
        ),
    ]
