# Generated by Django 3.1.3 on 2022-12-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_decimoterceiro_parcelasdecimoterceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('idFerias', models.AutoField(primary_key=True, serialize=False)),
                ('DataInicial', models.DateField(blank=True, null=True)),
                ('DataFinal', models.DateField(blank=True, null=True)),
                ('Concessão', models.IntegerField(default=0)),
                ('Periodo', models.IntegerField(default=0)),
                ('DiasPeriodo', models.IntegerField(default=0)),
                ('DataVencimento', models.DateField(blank=True, null=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'ferias',
                'ordering': ['idFerias'],
            },
        ),
    ]
