# Generated by Django 3.1.3 on 2021-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_vales_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrachequeitens',
            name='Vales_id',
            field=models.IntegerField(default=0),
        ),
    ]
