# Generated by Django 3.1.3 on 2022-12-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_ferias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='Concessão',
            new_name='Concessao',
        ),
    ]
