# Generated by Django 3.1.3 on 2023-01-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_auto_20221220_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='AquisitivoFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='AquisitivoInicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
