# Generated by Django 3.1.3 on 2021-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_contrachequeitens_vales_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrachequeitens',
            name='Referencia',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
