# Generated by Django 3.1.3 on 2021-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_contrachequeitens_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='ValeTransporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
