# Generated by Django 3.1.3 on 2023-01-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_auto_20230111_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='AquisitivoFinal',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='AquisitivoInicial',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='Concessao',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='DataVencimento',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='DiasPeriodo',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='Periodo',
        ),
        migrations.CreateModel(
            name='Aquisitivo',
            fields=[
                ('idAquisitivo', models.AutoField(primary_key=True, serialize=False)),
                ('DataInicial', models.DateField(blank=True, null=True)),
                ('DataFinal', models.DateField(blank=True, null=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'ferias_aquisitivo',
                'ordering': ['idAquisitivo'],
            },
        ),
    ]
