# Generated by Django 3.1.3 on 2021-06-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_salario_valetransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='ValeTransporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
