# Generated by Django 3.1.3 on 2023-01-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_auto_20230112_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='idAquisitivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.aquisitivo'),
            preserve_default=False,
        ),
    ]
