# Generated by Django 3.1.3 on 2021-06-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_auto_20210618_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='ValeTransporte',
        ),
    ]
