# Generated by Django 3.1.3 on 2023-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_ferias_idaquisitivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='Descricao',
            field=models.CharField(blank=15, max_length=15),
        ),
    ]
