# Generated by Django 3.1.3 on 2021-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0015_remove_salario_valetransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='ValeTransporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='contrachequeitens',
            name='Referencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
