# Generated by Django 3.1.3 on 2023-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0015_contracheque_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='Obs',
            field=models.TextField(blank=True),
        ),
    ]
