# Generated by Django 3.1.3 on 2025-02-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0017_alteracaosalarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoValeTransporte',
            fields=[
                ('idAlteracaoValeTransporte', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Obs', models.TextField(blank=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'salario_vale_transporte_alteracao',
                'ordering': ['idPessoal', 'Data'],
            },
        ),
    ]
