# Generated by Django 3.1.3 on 2025-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0018_alteracaovaletransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrachequeitens',
            name='Codigo',
            field=models.TextField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
