# Generated by Django 3.1.3 on 2025-05-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0019_contrachequeitens_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readmissao',
            fields=[
                ('idReadmissao', models.AutoField(primary_key=True, serialize=False)),
                ('DataAdmissao', models.DateField(blank=True, null=True)),
                ('DataDemissao', models.DateField(blank=True, null=True)),
                ('DataReadmissao', models.DateField(blank=True, null=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'readmissao',
                'ordering': ['DataReadmissao'],
            },
        ),
    ]
