# Generated by Django 3.1.3 on 2025-06-05 11:37

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0020_readmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpessoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pessoas.models.get_file_path),
        ),
    ]
