# Generated by Django 3.1.3 on 2025-06-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0021_docpessoal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialWebAuthn',
            fields=[
                ('idCredendialWebAuthn', models.AutoField(primary_key=True, serialize=False)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
        ),
    ]
