# Generated by Django 3.1.3 on 2025-06-22 19:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0022_credencialwebauthn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credencialwebauthn',
            options={'ordering': ['idPessoal']},
        ),
        migrations.AlterModelManagers(
            name='credencialwebauthn',
            managers=[
                ('pbjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name='credencialwebauthn',
            table='credenciais',
        ),
    ]
