# Generated by Django 3.2.25 on 2025-06-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0023_auto_20250622_1644'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='credencialwebauthn',
            managers=[
            ],
        ),
    ]
