# Generated by Django 3.1.3 on 2025-07-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0025_chavepublica'),
    ]

    operations = [
        migrations.CreateModel(
            name='FidoCredential',
            fields=[
                ('idFidoCredential', models.AutoField(primary_key=True, serialize=False)),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('public_key_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'credentials',
                'ordering': ['idPessoal'],
            },
        ),
    ]
