# Generated by Django 3.1.3 on 2025-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0026_fidocredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidocredential',
            name='devide_id',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fidocredential',
            name='liberado_pelo_rh',
            field=models.BooleanField(default=False),
        ),
    ]
