# Generated by Django 3.1.3 on 2025-07-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0027_auto_20250704_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fidocredential',
            name='devide_id',
        ),
    ]
