# Generated by Django 3.1.3 on 2025-07-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0028_remove_fidocredential_devide_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('idRegistroPonto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'Saída')], max_length=10)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'registro_ponto',
                'ordering': ['idPessoal', 'horario'],
            },
        ),
        migrations.RemoveField(
            model_name='credencialwebauthn',
            name='idPessoal',
        ),
        migrations.DeleteModel(
            name='ChavePublica',
        ),
        migrations.DeleteModel(
            name='CredencialWebAuthn',
        ),
    ]
