# Generated by Django 3.1.3 on 2025-07-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0029_auto_20250704_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidocredential',
            name='device_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
