# Generated by Django 3.1.3 on 2025-07-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0030_fidocredential_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhaAppPonto',
            fields=[
                ('idSenhaAppPonto', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=128)),
                ('idPessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoal')),
            ],
        ),
    ]
