# Generated by Django 3.1.3 on 2025-07-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0031_senhaappponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoal',
            name='registrado',
            field=models.BooleanField(default=False),
        ),
    ]
