# Generated by Django 3.1.3 on 2025-07-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0032_pessoal_registrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FidoCredential',
        ),
    ]
