# Generated by Django 3.1.3 on 2025-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0033_delete_fidocredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracheque',
            name='Descricao',
            field=models.CharField(max_length=15),
        ),
    ]
