# Generated by Django 3.1.3 on 2025-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0034_auto_20250728_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaoponto',
            name='Alteracao',
            field=models.CharField(default='ROBOT', max_length=9),
        ),
    ]
