# Generated by Django 3.1.3 on 2025-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0035_auto_20250730_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaoponto',
            name='Ausencia',
            field=models.CharField(blank=True, default='-------', max_length=7),
        ),
    ]
