# Generated by Django 3.1.3 on 2025-08-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0036_auto_20250730_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='BaseFGTS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='contracheque',
            name='BaseINSS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='contracheque',
            name='BaseIRRF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
