# Generated by Django 3.1.3 on 2025-08-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0037_auto_20250806_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='idContraCheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.contracheque'),
        ),
    ]
