# Generated by Django 3.1.3 on 2022-02-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220221_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
