# Generated by Django 3.1.3 on 2022-02-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
