# Generated by Django 3.1.3 on 2022-02-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['DescricaoUpload']},
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='Descricao',
            new_name='DescricaoUpload',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='upLoadFile',
            new_name='uploadFile',
        ),
    ]
