# Generated by Django 3.1.3 on 2022-07-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_auto_20220221_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasClientes',
            fields=[
                ('idNotasClientes', models.AutoField(primary_key=True, serialize=False)),
                ('DataColeta', models.DateField(default=0)),
                ('LocalColeta', models.CharField(max_length=200)),
                ('NumeroNota', models.CharField(default=0, max_length=15)),
                ('Destinatario', models.CharField(blank=True, max_length=200, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('Cidade', models.CharField(default='SÃO PAULO', max_length=30)),
                ('Estado', models.CharField(default='SP', max_length=2)),
                ('Volume', models.IntegerField(default=0)),
                ('Peso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('StatusNota', models.CharField(max_length=15)),
                ('Historico', models.TextField(blank=True, default='', null=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'notas_cliente',
            },
        ),
    ]
