# Generated by Django 3.1.3 on 2022-07-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasclientes',
            name='CEP',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
