# Generated by Django 3.1.3 on 2022-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0003_auto_20220727_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasclientes',
            name='Contato',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notasclientes',
            name='Informa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
