# Generated by Django 3.1.3 on 2022-08-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0004_auto_20220815_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasOcorrencias',
            fields=[
                ('idNotasOcorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('DataOcorrencia', models.DateField(default=0)),
                ('Descricao', models.TextField(blank=True, default='', null=True)),
                ('DataAgendada', models.DateField(default=0)),
                ('idNotasClientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romaneios.notasclientes')),
            ],
            options={
                'db_table': 'notas_ocorrencia',
            },
        ),
    ]
