# Generated by Django 3.1.3 on 2022-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0005_notasocorrencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasocorrencias',
            name='TipoOcorrencia',
            field=models.CharField(default='PENDENTE', max_length=25),
        ),
    ]
