# Generated by Django 3.1.3 on 2022-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0006_notasocorrencias_tipoocorrencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notasocorrencias',
            old_name='Descricao',
            new_name='Ocorrencia',
        ),
        migrations.AlterField(
            model_name='notasclientes',
            name='StatusNota',
            field=models.CharField(max_length=25),
        ),
    ]
