# Generated by Django 3.1.3 on 2022-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0008_romaneionotas_romaneios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romaneios',
            old_name='idmotorista',
            new_name='idMotorista',
        ),
    ]
