# Generated by Django 3.1.3 on 2023-03-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0011_auto_20220904_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasclientes',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='notasclientes',
            name='SerieNota',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
