# Generated by Django 3.1.3 on 2023-03-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220221_0900'),
        ('romaneios', '0012_auto_20230320_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneios',
            name='idCliente',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
