# Generated by Django 3.1.3 on 2023-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0013_romaneios_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasclientes',
            name='Emitente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
