# Generated by Django 3.1.3 on 2024-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneios', '0015_auto_20230526_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasclientes',
            name='Informa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
