# Generated by Django 3.1.3 on 2021-02-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CategoriaVeiculo',
                'ordering': ['Categoria'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idVeiculo', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=35)),
                ('Modelo', models.CharField(max_length=50)),
                ('Placa', models.CharField(max_length=8)),
                ('Cor', models.CharField(blank=True, max_length=15)),
                ('Ano', models.CharField(blank=True, max_length=4)),
                ('Renavam', models.CharField(blank=True, max_length=20)),
                ('Combustivel', models.CharField(blank=True, max_length=15)),
                ('Rastreador', models.CharField(blank=True, max_length=15)),
                ('RNTRC', models.CharField(blank=True, max_length=15)),
                ('Capacidade', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('MedidaAltura', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('MedidaComprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('MedidaLargura', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.categoriaveiculo')),
                ('Motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PessoalMotorista', to='pessoas.pessoal')),
                ('Proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PessoalProprietario', to='pessoas.pessoal')),
            ],
            options={
                'db_table': 'Veiculo',
                'ordering': ['Placa'],
            },
        ),
    ]
