# Generated by Django 3.1.3 on 2020-12-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='Comentario',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='VencimentoFatura',
        ),
    ]
