# Generated by Django 3.1.3 on 2022-02-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fatura',
            table='fatura',
        ),
    ]
