# Generated by Django 3.1.3 on 2020-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0002_auto_20201202_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='Comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='VencimentoFatura',
            field=models.DateField(default=0),
        ),
    ]
