# Generated by Django 3.1.3 on 2020-12-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0002_fatura_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='VencimentoFatura',
        ),
    ]
