# Generated by Django 3.1.3 on 2020-12-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0003_auto_20201202_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='VencimentoFatura',
        ),
    ]
