# Generated by Django 3.1.3 on 2020-12-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0004_fatura_vencimentofatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='VencimentoFatura',
            field=models.DateField(default=1),
        ),
    ]
