# Generated by Django 3.1.3 on 2022-04-10 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0004_emailenviado_idfatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailenviado',
            name='DataEnviado',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
