# Generated by Django 3.1.3 on 2020-12-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0005_fatura_vencimentofatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='VencimentoFatura',
        ),
    ]
