# Generated by Django 3.1.3 on 2022-04-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0005_auto_20220410_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailenviado',
            name='DataEnviado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
