# Generated by Django 3.1.3 on 2020-12-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0006_remove_fatura_vencimentofatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatura',
            old_name='DataPagamento',
            new_name='VencimentoFatura',
        ),
    ]
