# Generated by Django 3.1.3 on 2022-04-10 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0006_auto_20220410_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailenviado',
            name='DataEnviado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
