# Generated by Django 3.1.3 on 2020-12-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0007_auto_20201203_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='VencimentoFatura',
        ),
    ]
