# Generated by Django 3.1.3 on 2020-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0009_remove_fatura_datapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='DataPagamento',
            field=models.DateField(default=0),
        ),
    ]
