# Generated by Django 3.1.3 on 2020-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0010_fatura_datapagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='DataPagamento',
        ),
    ]
