# Generated by Django 3.1.3 on 2020-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamentos', '0011_remove_fatura_datapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='DataPagamento',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
