# Generated by Django 3.1.3 on 2021-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='AjudanteCobraHoraExtra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
