# Generated by Django 3.0.3 on 2020-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='phkesc',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
