# Generated by Django 3.1.3 on 2021-11-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaveiculo',
            name='idCategoriaVeiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.categoriaveiculo'),
        ),
        migrations.AddField(
            model_name='tabelaveiculo',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tabelaperimetro',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tabelacapacidade',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tabela',
            name='idCliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tabela',
            name='idFormaPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.formapagamento', verbose_name='FORMA DE PAGAMENTO'),
        ),
        migrations.AddField(
            model_name='fonecontatocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='emailcontatocliente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
