# Generated by Django 3.1.3 on 2021-01-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontatocliente',
            name='RecebeFatura',
            field=models.BooleanField(default=False),
        ),
    ]
