# Generated by Django 3.1.3 on 2021-01-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_emailcontatocliente_recebefatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaveiculo',
            name='EntregaKGCobra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabelaveiculo',
            name='EntregaKGPaga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabelaveiculo',
            name='EntregaVolumeCobra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabelaveiculo',
            name='EntregaVolumePaga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
