# Generated by Django 3.0.3 on 2020-08-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_formapagamento_phkesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='phkesc',
        ),
        migrations.AddField(
            model_name='tabela',
            name='phkesc',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
