# Generated by Django 3.0.3 on 2020-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200830_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='phkesc',
            new_name='phkescCobra',
        ),
        migrations.AddField(
            model_name='tabela',
            name='phkescPaga',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
