# Generated by Django 3.1.3 on 2023-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220221_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='Seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
