# Generated by Django 3.1.3 on 2023-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_tabela_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='Seguro',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
