# Generated by Django 3.1.3 on 2021-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210121_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='phkescCobra',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='phkescPaga',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
