# Generated by Django 3.0.3 on 2020-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200909_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='Entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabela',
            name='EntregaKG',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabela',
            name='EntregaVolume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
