# Generated by Django 3.1.3 on 2024-10-25 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20230330_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='HoraInicialExtras',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
