# Generated by Django 3.1.3 on 2021-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20210130_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Fantasia',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
