# Generated by Django 3.0.3 on 2020-10-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20201003_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='Entrega',
            new_name='EntregaCobra',
        ),
        migrations.RenameField(
            model_name='tabela',
            old_name='EntregaKG',
            new_name='EntregaKGCobra',
        ),
        migrations.RenameField(
            model_name='tabela',
            old_name='EntregaVolume',
            new_name='EntregaVolumeCobra',
        ),
    ]
