# Generated by Django 3.1.3 on 2021-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210131_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Bairro',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cidade',
            field=models.CharField(blank=True, default='SÃO PAULO', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Endereco',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nome',
            field=models.CharField(max_length=60),
        ),
    ]
