# Generated by Django 3.0.3 on 2020-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20201015_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='EntregaKGPaga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabela',
            name='EntregaPaga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tabela',
            name='EntregaVolumePaga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
