site_name: Documentação Sistema Efetiva
theme:
  name: material

nav:
  - Início: index.md
  - Módulos:
      - Colaboradores:
          - Models: models.md
          - Facade: facade.md
          - Views: views.md
