site_name: Documentação Sistema Efetiva
theme:
  name: material
  locale: pt
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Modo Escuro
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
  features:
    - content.code.copy

nav:
  - Início: index.md
  - Módulos:
      - Core:
          - Constants:
                - core/constants/Evento.md
          - Tools:
                - core/tools/excluir_arquivo.md
                - core/tools/injetar_parametro_no_request_post.md
                - core/tools/modal_excluir_arquivo.md
                - core/tools/upload_de_arquivo.md
          - Views:
                - core/views/index_core.md
                - core/views/visualizar_arquivo.md
      - Colaboradores:
          - Models: pessoas/models.md
          - Facade:
              - pessoas/facade/atualizar_contra_cheque_pagamento.md
              - pessoas/facade/atualizar_ou_adicionar_contra_cheque_item.md
              - pessoas/facade/calcular_adiantamento.md
              - pessoas/facade/calcular_atrasos.md
              - pessoas/facade/calcular_conducao.md
              - pessoas/facade/calcular_decimo_terceiro_proporcional.md
              - pessoas/facade/calcular_dias_ferias_proporcionais.md
              - pessoas/facade/calcular_dsr.md
              - pessoas/facade/calcular_dsr_feriado.md
              - pessoas/facade/calcular_faltas.md
              - pessoas/facade/calcular_ferias_proporcionais.md
              - pessoas/facade/calcular_horas_extras.md
              - pessoas/facade/calcular_pagamento_ferias_proporcionais.md
              - pessoas/facade/calcular_salario.md
              - pessoas/facade/calcular_saldo_computavel.md
              - pessoas/facade/create_contexto_categorias.md
              - pessoas/facade/create_contexto_contra_cheque_adiantamento.md
              - pessoas/facade/create_contexto_contra_cheque_pagamento.md
              - pessoas/facade/create_contexto_eventos_rescisorios_colaborador.md
              - pessoas/facade/create_contexto_salario.md
              - pessoas/facade/data_demissao_html_data.md
              - pessoas/facade/faltas_periodo_aquisitivo.md
              - pessoas/facade/get_meses_ordem.md
              - pessoas/facade/get_or_create_contra_cheque.md
              - pessoas/facade/get_or_create_contra_cheque_itens.md
              - pessoas/facade/get_saldo_contra_cheque.md
              - pessoas/facade/meses_proporcionais_decimo_terceiro.md
              - pessoas/facade/meses_proporcionais_ferias.md
              - pessoas/facade/modal_pagar_contra_cheque.md
              - pessoas/facade/modal_salario_colaborador.md
              - pessoas/facade/salario_html_data.md
              - pessoas/facade/save_pagamento_contra_cheque.md
              - pessoas/facade/save_salario_colaborador.md
              - pessoas/facade/validar_modal_salario_colaborador.md
              - pessoas/facade/verificar_salario_colaborador.md
              - pessoas/facade/verificar_ultimo_pagamento.md
          - Views:
              - pessoas/views/index_pessoal.md
              - pessoas/views/alterar_salario_colaborador.md
      - Pagamentos:
          - Facade:
              - pagamentos/facade/create_contexto_meses_pagamento.md
          - Views:
              - pagamentos/views/index_pagamento.md
  - Tabelas:
      - tabelas/eventos_contra_cheque.md

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences
