site_name: Documentação Sistema Efetiva
theme:
  name: material
  locale: pt
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Modo Escuro
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
  features:
    - content.code.copy

nav:
  - Início: index.md
  - Módulos:
      - Colaboradores:
          - Models: pessoas/models.md
          - Facade:
              - pessoas/facade/calcular_decimo_terceiro_proporcional.md
              - pessoas/facade/calcular_dias_ferias_proporcionais.md
              - pessoas/facade/calcular_ferias_proporcionais.md
              - pessoas/facade/calcular_pagamento_ferias_proporcionais.md
              - pessoas/facade/create_contexto_eventos_rescisorios_colaborador.md
              - pessoas/facade/data_demissao_html_data.md
              - pessoas/facade/faltas_periodo_aquisitivo.md
              - pessoas/facade/meses_proporcionais_decimo_terceiro.md
              - pessoas/facade/meses_proporcionais_ferias.md
          - Views: pessoas/views.md
              - pessoas/facade/verificar_salario_colaborador.md
      - Pagamentos:
          - Facade:
              - pagamentos/facade/create_contexto_meses_pagamento.md
          - Views:
              - pagamentos/views/index_pagamento.md

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences
