# Generated by Django 3.1.3 on 2021-11-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('orcamentos', '0001_initial'),
        ('clientes', '0002_auto_20211105_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='idCategoriaVeiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.categoriaveiculo'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='idFormaPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.formapagamento'),
        ),
    ]
