# Generated by Django 3.1.3 on 2021-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='TaxaExpedicao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
