# Generated by Django 3.1.3 on 2021-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_taxaexpedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='StatusOrcamento',
            field=models.CharField(default='CRIADO', max_length=20),
        ),
    ]
