# Generated by Django 3.1.3 on 2022-02-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_auto_20211105_1305'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orcamento',
            table='orcamento',
        ),
    ]
