# Generated by Django 3.1.3 on 2021-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_auto_20210210_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ValorTabela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
