# Generated by Django 3.1.3 on 2021-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_orcamento_valortabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='QuantidadeAjudantes',
            field=models.IntegerField(default=0),
        ),
    ]
