# Generated by Django 3.1.3 on 2021-02-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('orcamentos', '0003_orcamento_statusorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='idFormaPagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.formapagamento'),
            preserve_default=False,
        ),
    ]
