# Generated by Django 3.1.3 on 2021-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_orcamento_quantidadeajudantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='QuantidadeAjudantes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
