# Generated by Django 3.1.3 on 2021-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_auto_20210213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='Ajudantes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='QuantidadeAjudantes',
            field=models.IntegerField(default=0),
        ),
    ]
