# Generated by Django 3.1.3 on 2021-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_auto_20210213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='StatusOrcamento',
            field=models.CharField(default='CRIADO', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='TaxaExpedicao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
