# Generated by Django 3.1.3 on 2021-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('idAbastecimento', models.AutoField(primary_key=True, serialize=False)),
                ('DataAbastecimento', models.DateField(default=0)),
                ('LitrosAbastecidos', models.PositiveIntegerField()),
                ('ValorAbastecido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ValorCombustivel', models.DecimalField(decimal_places=3, max_digits=6)),
                ('TipoCombustivel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Despesas_Abastecimento',
            },
        ),
    ]
