# Generated by Django 3.1.3 on 2021-08-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('idAbastecimento', models.AutoField(primary_key=True, serialize=False)),
                ('DataAbastecimento', models.DateField(default=0)),
                ('LitrosAbastecidos', models.PositiveIntegerField()),
                ('ValorAbastecido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ValorCombustivel', models.DecimalField(decimal_places=3, max_digits=6)),
                ('TipoCombustivel', models.CharField(max_length=10)),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
            options={
                'db_table': 'Despesas_Abastecimento',
            },
        ),
    ]
