# Generated by Django 3.1.3 on 2021-11-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='idVeiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo'),
        ),
    ]
