# Generated by Django 3.1.3 on 2022-05-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multas',
            name='idVeiculo',
        ),
        migrations.DeleteModel(
            name='Abastecimento',
        ),
        migrations.DeleteModel(
            name='Multas',
        ),
    ]
