# Generated by Django 3.1.3 on 2022-05-20 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0002_auto_20220221_0900'),
        ('despesas', '0002_auto_20220520_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroAIT', models.CharField(max_length=20)),
                ('NumeroDOC', models.CharField(blank=True, max_length=20, null=True)),
                ('DataMulta', models.DateField(default=0)),
                ('HoraMulta', models.TimeField(default=datetime.time(0, 0))),
                ('ValorMulta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Vencimento', models.DateField(default=0)),
                ('Infracao', models.CharField(max_length=100)),
                ('Local', models.CharField(max_length=240)),
                ('Pago', models.BooleanField(default=False)),
                ('DescontaMotorista', models.BooleanField(default=False)),
                ('DataPagamento', models.DateField(default=0)),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('idAbastecimento', models.AutoField(primary_key=True, serialize=False)),
                ('DataAbastecimento', models.DateField(default=0)),
                ('LitrosAbastecidos', models.PositiveIntegerField()),
                ('ValorAbastecido', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ValorCombustivel', models.DecimalField(decimal_places=3, max_digits=6)),
                ('TipoCombustivel', models.CharField(max_length=10)),
                ('Pago', models.BooleanField(default=False)),
                ('DataPagamento', models.DateField(default=0)),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
            options={
                'db_table': 'abastecimento',
            },
        ),
    ]
