# Generated by Django 3.1.3 on 2022-02-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_abastecimento_idveiculo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abastecimento',
            table='abastecimento',
        ),
    ]
