# Generated by Django 3.1.3 on 2022-06-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_abastecimento_multas'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='LinhaDigitavel',
            field=models.CharField(blank=True, max_length=47, null=True),
        ),
    ]
