# Generated by Django 3.1.3 on 2022-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_multas_linhadigitavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='LinhaDigitavelSP',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
