# Generated by Django 3.1.3 on 2022-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_multas_linhadigitavelsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id_Despesa', models.AutoField(primary_key=True, serialize=False)),
                ('Cedente', models.CharField(max_length=200)),
                ('Categoria', models.CharField(max_length=100)),
                ('SubCategoria', models.CharField(max_length=100)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Vencimento', models.DateField(default=0)),
                ('DataPgto', models.DateField(default=0)),
                ('ValorPago', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
    ]
