# Generated by Django 3.1.3 on 2022-07-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_auto_20220715_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'despesas_categoria',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('idSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('SubCategoria', models.CharField(max_length=100)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.categoria')),
            ],
            options={
                'db_table': 'despesas_subcategoria',
            },
        ),
    ]
