# Generated by Django 3.1.3 on 2022-07-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0008_categoria_subcategoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='SubCategoria',
            new_name='SubCategorias',
        ),
    ]
