# Generated by Django 3.1.3 on 2022-07-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0009_auto_20220718_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.categorias'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='SubCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.subcategorias'),
        ),
    ]
