# Generated by Django 3.1.3 on 2023-03-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220221_0900'),
        ('despesas', '0011_auto_20230307_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
