# Generated by Django 3.1.3 on 2023-03-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_ferias_idaquisitivo'),
        ('clientes', '0003_auto_20220221_0900'),
        ('despesas', '0012_multas_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multas',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='multas',
            name='idPessoal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoal'),
        ),
        migrations.AlterField(
            model_name='multas',
            name='idVales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.vales'),
        ),
    ]
