from django.urls import path

from .views import (
    adiantamento,
    adiantamento_automatico,
    adiciona_agenda,
    adiciona_contra_cheque_itens,
    adiciona_vales,
    altera_horario_cartao_ponto,
    apagar_tudo,
    atestada,
    ausencia_falta,
    carrega_agenda,
    carro_empresa,
    cria_contrachequeitens,
    cria_contrachequeitensvale,
    cria_folha,
    cria_pagamento,
    cria_vale,
    delete_file,
    edita_cartaoponto,
    exclui_agenda,
    exclui_contrachequeitens,
    exclui_contrachequeitensvale,
    exclui_recibo,
    exclui_vale,
    imprime_contracheque,
    imprime_recibo,
    index_pagamento,
    inserefalta,
    manutencao,
    print_contra_cheque_adiantamento,
    print_contra_cheque_pagamento,
    print_contra_cheque_transporte,
    remove_contra_cheque_itens,
    remove_vales,
    salva_file,
    seleciona_contracheque,
    seleciona_folha,
    seleciona_funcionario,
    seleciona_mes_ano,
    seleciona_periodo,
    seleciona_saldoavulso,
    seleciona_vales,
)

urlpatterns = [
    path("", index_pagamento, name="index_pagamento"),
    path("criafolha", cria_folha, name="criafolha"),
    path("selecionafolha", seleciona_folha, name="selecionafolha"),
    path("selecionacontracheque", seleciona_contracheque, name="selecionacontracheque"),
    path("criacontrachequeitens", cria_contrachequeitens, name="criacontrachequeitens"),
    path(
        "excluicontrachequeitens",
        exclui_contrachequeitens,
        name="excluicontrachequeitens",
    ),
    path("inserefalta", inserefalta, name="inserefalta"),
    path(
        "editacartaoponto/<int:idcartaoponto>/",
        edita_cartaoponto,
        name="editacartaoponto",
    ),
    path("selecionaperiodo", seleciona_periodo, name="selecionaperiodo"),
    path("selecionasaldoavulso", seleciona_saldoavulso, name="selecionasaldoavulso"),
    path("criapagamento", cria_pagamento, name="criapagamento"),
    path("criavale", cria_vale, name="criavale"),
    path("excluivale", exclui_vale, name="excluivale"),
    path("excluirecibo", exclui_recibo, name="excluirecibo"),
    path("imprimerecibo", imprime_recibo, name="imprimerecibo"),
    path(
        "criacontrachequeitensvale",
        cria_contrachequeitensvale,
        name="criacontrachequeitensvale",
    ),
    path(
        "excluicontrachequeitensvale",
        exclui_contrachequeitensvale,
        name="excluicontrachequeitensvale",
    ),
    path("imprimecontracheque/", imprime_contracheque, name="imprimecontracheque"),
    path("manutencao", manutencao),
    path("apaga", apagar_tudo, name="apaga"),
    path(
        "seleciona_mes_ano",
        seleciona_mes_ano,
        name="seleciona_mes_ano",
    ),
    path(
        "seleciona_funcionario",
        seleciona_funcionario,
        name="seleciona_funcionario",
    ),
    path(
        "ausencia_falta",
        ausencia_falta,
        name="ausencia_falta",
    ),
    path(
        "altera_horario_cartao_ponto",
        altera_horario_cartao_ponto,
        name="altera_horario_cartao_ponto",
    ),
    path(
        "atestada",
        atestada,
        name="atestada",
    ),
    path(
        "adiantamento",
        adiantamento,
        name="adiantamento",
    ),
    path(
        "adiantamento_automatico",
        adiantamento_automatico,
        name="adiantamento_automatico",
    ),
    path(
        "adiciona_contra_cheque_itens",
        adiciona_contra_cheque_itens,
        name="adiciona_contra_cheque_itens",
    ),
    path(
        "remove_contra_cheque_itens",
        remove_contra_cheque_itens,
        name="remove_contra_cheque_itens",
    ),
    path(
        "adiciona_vales",
        adiciona_vales,
        name="adiciona_vales",
    ),
    path(
        "seleciona_vales",
        seleciona_vales,
        name="seleciona_vales",
    ),
    path(
        "remove_vales",
        remove_vales,
        name="remove_vales",
    ),
    path(
        "print_contra_cheque_pagamento",
        print_contra_cheque_pagamento,
        name="print_contra_cheque_pagamento",
    ),
    path(
        "print_contra_cheque_adiantamento",
        print_contra_cheque_adiantamento,
        name="print_contra_cheque_adiantamento",
    ),
    path(
        "print_contra_cheque_transporte",
        print_contra_cheque_transporte,
        name="print_contra_cheque_transporte",
    ),
    path(
        "salva_file",
        salva_file,
        name="salva_file",
    ),
    path(
        "delete_file",
        delete_file,
        name="delete_file",
    ),
    path(
        "carro_empresa",
        carro_empresa,
        name="carro_empresa",
    ),
    path(
        "adiciona_agenda",
        adiciona_agenda,
        name="adiciona_agenda",
    ),
    path(
        "carrega_agenda",
        carrega_agenda,
        name="carrega_agenda",
    ),
    path(
        "exclui_agenda",
        exclui_agenda,
        name="exclui_agenda",
    ),
]
