from django.urls import path

from .views import (
    adiciona_nota_cliente,
    adiciona_nota_romaneio,
    adiciona_ocorrencia,
    adiciona_romaneio,
    edita_nota_cliente,
    edita_romaneio,
    exclui_nota_cliente,
    index_romaneio,
    ocorrencia_nota_cliente,
    seleciona_cliente,
    seleciona_romaneio,
)

urlpatterns = [
    path(
        "",
        index_romaneio,
        name="index_romaneio",
    ),
    path(
        "seleciona_cliente",
        seleciona_cliente,
        name="seleciona_cliente",
    ),
    path(
        "adiciona_nota_cliente",
        adiciona_nota_cliente,
        name="adiciona_nota_cliente",
    ),
    path(
        "edita_nota_cliente",
        edita_nota_cliente,
        name="edita_nota_cliente",
    ),
    path(
        "exclui_nota_cliente",
        exclui_nota_cliente,
        name="exclui_nota_cliente",
    ),
    path(
        "ocorrencia_nota_cliente",
        ocorrencia_nota_cliente,
        name="ocorrencia_nota_cliente",
    ),
    path(
        "adiciona_ocorrencia",
        adiciona_ocorrencia,
        name="adiciona_ocorrencia",
    ),
    path(
        "adiciona_romaneio",
        adiciona_romaneio,
        name="adiciona_romaneio",
    ),
    path(
        "edita_romaneio",
        edita_romaneio,
        name="edita_romaneio",
    ),
    path(
        "seleciona_romaneio",
        seleciona_romaneio,
        name="seleciona_romaneio",
    ),
    path(
        "adiciona_nota_romaneio",
        adiciona_nota_romaneio,
        name="adiciona_nota_romaneio",
    ),
]
